// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment
// This is a dummy comment

fn main() {
    println!("Hello, world!");
}
